### ISSUE TITLE
Anyone using this / still working on it?

### ISSUE THREAD

**Issue by MarkPieszak** [yargalot/Angular-HMR#4]
Anyone using or still working on this? @yargalot

**Comment by xbill82** [comment]
Hi @MarkPieszak 
I just forked the repo since I'm switching an AngularJS project to webpack with HMR.
I've already applied a couple of bugfixes that stuck the loader with directives and constants (actually, one of my fixes is quite similar to #3 ). The code is clean, thanks @yargalot!
I plan to write a proper HOWTO to make the setup easier for newcomers.
Of course, if @yargalot wants to keep maintaining this repo, I'll be glad to submit my PRs.

Oh, and I noticed that there are some more forks, but didn't take the time to see what's been done.

**Comment by MarkPieszak** [comment]
@xbill82 Very nice! I currently have a webpack Angular setup myself, but of course only style changes work for the HMR :( 

Checking out your repo now, is it working with components & ui-router as well?

**Comment by yargalot** [comment]
Hey sorry about not getting back to this, slipped my mind, started a new job this week. Project is still maintained, happy to take prs then publish it to npm. Readme does need work, and probably explanations around why singletons wont hot reload, can look into that this weekend :)

**Comment by MarkPieszak** [comment]
@yargalot Great! Glad to hear it's not dead :) :+1: 
I'd be glad to help as well with some issues.
Hey, as long as some changes in Angular work, component changes, module changes, that's good enough for me!

**Comment by xbill82** [comment]
Hi @yargalot glad to see you back! Congrats for your new job.
I will submit my PRs as soon as possible. Thrilled to see this on npm!

**Comment by yargalot** [comment]
PR merged @xbill82, let me know if there is anything else, can do a quick release now. 

Will put some work into the repo this weekend to make work with components. I think it should work with ui-router @MarkPieszak but I'll double check on that

**Comment by xbill82** [comment]
Awesome!
we are currently on early test stage so I'll come up with PRs as things appear. I think an NPM release would be totally legit (as long as the version number stays "prudent" -> 0.x :)

**Comment by yargalot** [comment]
Righto, will release now then :)

**Comment by yargalot** [comment]
Right thats up https://www.npmjs.com/package/angular-hmr

**Comment by xbill82** [comment]
:clap:

**Comment by xbill82** [comment]
we can close this issue then?

**Comment by yargalot** [comment]
Sounds good, lets make other issues for anything else you guys find

**Comment by vitaliy-bobrov** [comment]
I've forked this project and add some improvements
https://github.com/vitaliy-bobrov/angular-hot-loader
